### PR TITLE
Add Databricks SQL connector

### PR DESCRIPTION
**Pull request by DanFitzgibbon**
## Summary

This PR aims to add [Databricks SQL](https://www.databricks.com/product/databricks-sql) as a new connector for Briefer, solving #133.

Since this is a draft and open for discussion on what might be assumed or not in terms of catalog usage, schema definitions and whether writeback or other attributes are being properly done (or need to), all feedback is thoroughly welcome.

Update 2024.10.09: All of the things from the checklist have been done, theoretically - will now proceed to test this further.

### Backend
- [x] Add to Prisma schema file
- [x] Add database driver to `jupyter-requirements.txt`
- [x] Add database driver to API dependencies
- [x] Update authentication for new data source
- [x] Create data source handler
- [x] Update structure and data handlers

### Frontend
- [x] Add data source icon
- [x] Update data source icon list
- [x] Update data source list
- [x] Update hooks for new data source
- [x] Update data source pages
- [x] Create new data source form

### Extras
- [x] Migration query for the API db

### CODE REVIEW

**Comment by DanFitzgibbon** [comment]
I actually can't believe I'm writing this but props to you folks for making the process so ezpz!
image

**Comment by DanFitzgibbon** [comment]
I've yet to sign the CLA, yes, I'm just double checking some things. But would love some 👀 !

**Comment by lucasfcosta** [comment]
Hey @DanFitzgibbon! This is looking amazing! Thank you for submitting this contribution.

Just double checking: I see you marked all tasks as ready. Can you confirm it's ready for review so we can test and take a deeper look at the code?

**Comment by DanFitzgibbon** [comment]
Will just resolve the conflicts but feel free to look at it!

**Comment by DanFitzgibbon** [comment]
Hi @lucasfcosta! Conflicts resolved and ready for review!

**Comment by DanFitzgibbon** [comment]
Any news here? Would love to be able to use this in prod without going through the hassle of making the build everytime.

**Comment by DanFitzgibbon** [comment]
Hey @lucasfcosta, any news here? Would love to be able to use this in prod without going through the hassle of making the build every time.

**Comment by lucasfcosta** [comment]
Hey @DanFitzgibbon! I'm going to try and review this before the end of next week - it's been really busy with all the new sign-ups but I'll do everything I can to merge this ASAP!

**Review by vieiralucas — APPROVED** [review]
Hi @DanFitzgibbon just reviewed this with @lucasfcosta 
This is awesome, thank you so much for this. It LGTM.

**Comment by lucasfcosta** [comment]
@DanFitzgibbon this is now merged! Thank you so much for this - we love it 💚

This should be out via tag `v0.0.54` now. Can you let me know if everything is working fine for you in this version?

PS: Any chance you'd be up for giving us feedback on how you've been using Briefer + Databricks? That would be super helpful to us! [I've got a Calendly here if you're up for that](https://calendly.com/lucasfcosta/1-1-lucas-blocks).

**Pull request merged**
