### PR TITLE
feat: adding a message while loading a new data source

### PR DESCRIPTION
**Pull request by Samuel-Brito19**
[Screencast from 2024-09-17 08-20-55.webm](https://github.com/user-attachments/assets/d1de98f3-226d-426b-a312-ebcf5ff6385b)

Issue: #70

### CODE REVIEW

**Comment by lucasfcosta** [comment]
Hey Samuel! Thanks so much for this PR, I think we had a small misunderstanding regarding what this issue was about.

This issue relates exclusively to pinging a data source - meaning that what we should do is replace the "online" or "offline" message with pinging.

That's the part that needs to be changed:

Screenshot 2024-09-17 at 19 19 54

**Review by lucasfcosta — CHANGES_REQUESTED** [review]
Hey Samuel! Thanks for this PR! I think we had a small misunderstanding regarding what this issue was about though.

This is not about the loading for the data sources list, but the "loading" state for the _ping_ specifically, which happens when you explicitly ping a data source. It also happens automatically after adding one.

See the image below for more info. Does that make more sense?

Screenshot 2024-09-17 at 19 19 54

Please lmk if you have questions

**Comment by Samuel-Brito19** [comment]
Oh, I'm sorry. But how can I reproduce this error?

**Comment by vieiralucas** [comment]
Hello @Samuel-Brito19, do you think you'll be able to make the adjustments suggested here?
If not, just let me know and I'll pick up your branch and finish this so we can close #70 

Thank you.

**Comment by Samuel-Brito19** [comment]
I'll continue! Sorry for the time, I was busy.

**Comment by vieiralucas** [comment]
Thanks @Samuel-Brito19

**Pull request merged**
